export { buildLineDiffRows } from './buildLineDiffRows'
export type { CodeBlockHeaderRenderProps, CodeBlockWithGutterProps } from './components/CodeBlockWithGutter'
export { CodeBlockWithGutter } from './components/CodeBlockWithGutter'
export type { FileDiffHeaderRenderProps, FileDiffSectionProps } from './components/FileDiffSection'
export { FileDiffSection } from './components/FileDiffSection'
export type { MultiFileDiffProps } from './components/MultiFileDiff'
export { MultiFileDiff } from './components/MultiFileDiff'
export { langFromFileName } from './langFromFileName'
export { splitSourceLines } from './splitSourceLines'
export type { DiffRow, DiffRowKind, FileContents, FileDiffPair } from './types'
